# Docker Compose version declaration is obsolete in newer versions
# Keeping for compatibility but can be removed

services:
  coach-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coach-app-frontend
    ports:
      # Metro bundler
      - "8081:8081"
      # Expo DevTools
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Use named volume for node_modules to avoid conflicts
      - node_modules:/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - NODE_ENV=development
      - EXPO_PUBLIC_API_URL=http://laravel.test/api
    networks:
      - coach_sail
    stdin_open: true
    tty: true
    command: npm start

volumes:
  node_modules:

networks:
  coach_sail:
    external: true
